server:
  port: 8081
  servlet:
    context-path: /api
  error:
    include-message: always
    include-stacktrace: on_param

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5433/chat-app

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/realms/chat-app

  flyway:
    user: postgres
    password: postgres
    schemas: chat-app-backend

management:
  endpoints:
    web:
      exposure:
        include: '*'
